EMAIL_FIELD = '//*[@id="i0116"]'
EMAIL_NEXT_BUTTON = '//*[@id="idSIButton9"]'
PASSWD_FIELD = '//*[@id="i0118"]'
SIGNIN_BUTTON = '//*[@id="idSIButton9"]'
REM_LOGIN_BUTTON = '//*[@id="idSIButton9"]'
WEBCAM_TOGGLE = '//*[@id="page-content-wrapper"]/div[1]/div/calling-pre-join-screen/div/div/div[2]/div[1]/div[2]/div/div/section/div[2]/toggle-button[1]/div/button/span[1]'
MIC_TOGGLE = '//*[@id="preJoinAudioButton"]/div/button/span[1]'
JOIN_NOW_BUTTON = '//*[@id="page-content-wrapper"]/div[1]/div/calling-pre-join-screen/div/div/div[2]/div[1]/div[2]/div/div/section/div[1]/div/div/button'
TEAMS_BUTTON = '//*[@id="teams-app-bar"]/ul/li[2]'
HANGUP_BUTTON = '//*[@id="hangup-button"]'

CHAT_BUTTON = '//*[@id="chat-button"]'
CHATBOX_FIELD = '.cke_wysiwyg_div > div'
CHATBOX_SEND = '//*[@id="send-message-button"]'
CHATBOX_CLOSE = '//*[@id="page-content-wrapper"]/div[1]/div/calling-screen/div/div[2]/meeting-panel-components/calling-chat/div/right-pane-header/div/div/button/svg-include/svg'
CONTINUE_BUTTON = '.ts-btn-fluent-secondary-alternate'
MIC_MUTED_CROSS = '.icon > .icons-close'
CALLING_MONITOR = '//calling-monitor/div/div/div/div'
